# Categorical Crossentropy Test

In [2]:
import tensorflow as tf

assert tf.executing_eagerly()

In [15]:
y = tf.constant([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [16]:
y_out = tf.constant([[0.29306632, 0.12683341, 0.23659508, 0.3048356 , 0.03866955],
       [0.29306632, 0.12683341, 0.23659508, 0.3048356 , 0.03866955],
       [0.02576115, 0.18275638, 0.04128503, 0.02768068, 0.72251683],
       [0.26704115, 0.16870402, 0.23757927, 0.27100047, 0.05567515],
       [0.29306632, 0.12683341, 0.23659508, 0.3048356 , 0.03866955],
       [0.29306632, 0.12683341, 0.23659508, 0.3048356 , 0.03866955]])

In [17]:
y1_error = tf.math.multiply(-y, tf.math.log(y_out))
print(y1_error)

tf.Tensor(
[[1.2273563  0.         0.         0.         0.        ]
 [1.2273563  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.32501456]
 [0.         0.         1.437254   0.         0.        ]
 [1.2273563  0.         0.         0.         0.        ]
 [1.2273563  0.         0.         0.         0.        ]], shape=(6, 5), dtype=float32)


In [18]:
y0_error = tf.math.multiply(1 - y, tf.math.log(1 - y_out))
print(y0_error)

tf.Tensor(
[[-0.         -0.13562895 -0.26996672 -0.36360687 -0.03943704]
 [-0.         -0.13562895 -0.26996672 -0.36360687 -0.03943704]
 [-0.02609876 -0.20181802 -0.04216147 -0.02807103 -0.        ]
 [-0.31066573 -0.18476939 -0.         -0.31608224 -0.05728505]
 [-0.         -0.13562895 -0.26996672 -0.36360687 -0.03943704]
 [-0.         -0.13562895 -0.26996672 -0.36360687 -0.03943704]], shape=(6, 5), dtype=float32)


In [28]:
error = tf.math.subtract(y1_error, y0_error)
print(error)

tf.Tensor(
[[1.2273563  0.13562895 0.26996672 0.36360687 0.03943704]
 [1.2273563  0.13562895 0.26996672 0.36360687 0.03943704]
 [0.02609876 0.20181802 0.04216147 0.02807103 0.32501456]
 [0.31066573 0.18476939 1.437254   0.31608224 0.05728505]
 [1.2273563  0.13562895 0.26996672 0.36360687 0.03943704]
 [1.2273563  0.13562895 0.26996672 0.36360687 0.03943704]], shape=(6, 5), dtype=float32)


In [30]:
print(tf.keras.backend.sum(error, 1))
print(sum([1.2273563,  0.13562895, 0.26996672, 0.36360687, 0.03943704]))

tf.Tensor([2.035996  2.035996  0.6231638 2.3060563 2.035996  2.035996 ], shape=(6,), dtype=float32)
2.03599588


In [32]:
print(tf.math.reduce_mean(error))
print(sum([1.2273563,  0.13562895, 0.26996672, 0.36360687, 0.03943704]))

tf.Tensor(0.3691068, shape=(), dtype=float32)
2.03599588


In [31]:
tf.keras.losses.categorical_crossentropy.__name__

'categorical_crossentropy'